server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5400/microservice
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import: configserver:http://localhost:8085

okta:
  oauth2:
    issuer: https://dev-26813248.okta.com/oauth2/default
    audience: api://default

#eureka:
#  instances:
#    prefer-ip-address: true
#
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka